name: Validate Iris Sample

on:
  push:
    paths:
      - 'iris.csv'
  pull_request:
    paths:
      - 'iris.csv'

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install Dependencies
      run: pip install -r requirements.txt

    - name: Validate New Iris Sample
      run: python validate.py
